import os

HOMEPAGE = os.getenv('HOMEPAGE')
SUPPORT_EMAIL = os.getenv('SUPPORT_EMAIL')
EMAIL_NOTIFICATION_SENDER = os.getenv('EMAIL_NOTIFICATION_SENDER')
EMAIL_LOGO_PATH = os.getenv('EMAIL_LOGO_PATH')
