# Generated by Django 3.2.4 on 2021-06-12 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210612_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='telephone',
            field=models.CharField(default='0912265299', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newscomment',
            name='content',
            field=models.TextField(),
        ),
    ]
